# Pipeline definition for CD after the CI pipeline runs.
trigger: none

resources:
  pipelines:
    - pipeline: az-vote-ci
      source: "arc-cicd-demo-src CI"
      trigger:
        branches:
          - master
  repositories:
    - repository: Manifest
      type: git # Set to 'github' for a GitHub repository 
      name: azure-vote-app-deployment
      ref: 'refs/heads/dev'

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  - group: az-vote-app-dev
  - name: images_artifact_path
    value: $(Pipeline.Workspace)/az-vote-ci/image_tags
  - name: manifests_artifact_path
    value: $(Pipeline.Workspace)/az-vote-ci/manifests
  - name: utils_artifact_path
    value: $(Pipeline.Workspace)/az-vote-ci/utils
  - name: REPO_URL 
    value: https://csedevops@dev.azure.com/csedevops/GitOps/_git/azure-vote-app-deployment
  - name: OrganizationName
    value: csedevops
  - name: MANIFEST_DIR
    value: $(System.DefaultWorkingDirectory)/azure-vote-app-deployment
  - name: DEPLOY_BRANCH_NAME
    value: deploy/$(Build.BuildNumber)/$(MANIFESTS_BRANCH)
  - name: PROJECT_NAME
    value: GitOps
  - name: REPO_NAME
    value: azure-vote-app-deployment

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "deploy_dev"
    displayName: "Deploy to Dev"
    jobs:
      - deployment: Deploy_to_dev
        displayName: "Deploy to Dev"
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: deployment-template.yaml

  - stage: "deploy_stage"
    displayName: "Deploy to Stage"
    variables:
      - group: az-vote-app-stage
    jobs:
      - deployment: Deploy_to_stage
        displayName: "Deploy to Stage"
        environment: stage
        strategy:
          runOnce:
            deploy:
              steps:
                - template: deployment-template.yaml
