steps:
  - task: AzureCLI@1        
    name: "smoke_test"
    displayName: "Smoke Test"
    inputs:
      azureSubscription: $(AZURE_SUBSCRIPTION)
      scriptType: bash
      scriptLocation: utils/smoke-test.sh
